settings:
    loginUrl: "https://login.salesforce.com/services/oauth2/token?grant_type=password"
    clientId: "clientId"
    clientSecret: "clientSecret"
    userName: "username"
    passWord:  "password"
    flaskhost: 0.0.0.0
    flaskport: 5001
    logfilename: sfapi.log
    logmaxBytes: 100000
    logbackupCount: 5
    objectstovaliadte:
      - account
      - opportunity


